---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections: 
upload_dir: content/media
public_path: "/media"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: 0.42.1
