---
hide_body: false
is_partial: false
fields:
- type: text
  default: Title
  config:
    required: true
- type: datetime
  name: date
  label: date
  config:
    date_format: YYYY-MM-DD
    display_utc: true
    required: true
- type: tag_list
  label: categories
  name: categories
pages:
- content/post/first-day-with-kubernetes.md
